# Sorting

In [1]:
import time                       #Python time module allows you to work with all time-related functions.
import numpy as np
np.random.seed(0)                 #same set of random numbers

### Insertion Sort

In [2]:
def insertion_sort(arr):                       #define function that uses insertion sort to order an array
    
    for j in range(1,len(arr)):                #para la variable  j en un rango de 1 a la longitud de n, en pasos de 1
        key=arr[j]                             #defino la variable key para guardar el valor de la posición j en mi arreglo m
        i=j-1                                  #defino i como la posicion anterior a j
        while i >= 0 and arr[i] > key:         #mientras que i >= 0 y la posicion i de mi arreglo > key
            arr[i+1]=arr[i]                    #en la posicion i+1 pongo el valor de 
            i=i-1                              #redefino i como el valor i anterior -1
        arr[i+1]=key                           #pongo en la posicion i+1 a key
    return arr

In [3]:
#This method is just to calculate the time, if you don't need it, don't worry
def insertion_algorithm(arr):
    start = time.time()
    insertion_sort(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [4]:
data = np.random.randint(1,10000,17000)       #hace un arreglo de 17000 elementos aleatorios entre 1 y 10000

In [5]:
insertion_algorithm(data)

The time of execution of above program is : 15530.068397521973 ms for a size of  17000


array([   1,    1,    1, ..., 9999, 9999, 9999])

### Merge Sort

In [6]:
def merge_sort(arr):                       #defino la función merge_sort que tendrá como argumento un array
    if len(arr)>1:                         #si la longitud de este array es mayor que 1
        mid=len(arr)//2                    #tomo esta longitud y calculo la mitad aproximando al menor entero
        left=arr[:mid]                     #divido el array en la parte izq
        right=arr[mid:]                    #y en la parte derecha
        
        merge_sort(left)                   #aplico el metodo a la parte izq
        merge_sort(right)                  #y a la parte der
        
        i = j = k = 0                      #defino valores inicales para las variables i, j, k

        while i < len(left) and j < len(right):          #mientras i < la longitud de left y m < que la longitud de right
            if left[i] < right[j]:                       #si el valor en i de left es menor que el valor en j de right
                arr[k] = left[i]                         #k de arr será i de left
                i += 1                                   #sumo 1 al valor ya existente de i
            else:                                        #si el valor en i de left NO es menor que el valor en j de right
                arr[k] = right[j]                          #k de arr será J de left
                j += 1                                   #sumo 1 al valor ya existente de j
            k += 1                                       #sumo 1 al valor ya existente de k
            
            #mientras se alcanza el final de left y right, sus elementos se ubican correctamente en el arreglo arr inicial

        while i < len(left):                             #mientras i sea menor que la longitud de left
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1
    return(arr)
        

In [7]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    merge_sort(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [8]:
data = np.random.randint(1,10000,17000)

In [9]:
merge_algorithm(data)

The time of execution of above program is : 84.70630645751953 ms for a size of  17000


array([   1,    1,    1, ..., 1872, 1872, 2844])

### Algorithm of your choice: Radix Sort

Know implement another algorithm, anyone works. Use the same size of data.

Radix sort works by sorting each digit from least significant digit to most significant digit. So in base 10 (the decimal system), radix sort would sort by the digits in the 1's place, then the 10’s place, and so on.

In [10]:
def counting_sort(arr, place):                #radix sort uses counting sort as a subroutine to order 
    size = len(arr)                           #define size as the lenght of the array
    output = [0] * size                         #create an array of zeros with the same size of the array 
    count = [0] * 10                            #create an array of ceros of lenght 10 to store the frecuency of the digits

    for i in range(0, size):                    #calculate count of elements 
        index = arr[i] // place               #index is the value of the position i divided by place
        count[index % 10] += 1                  #count index module 10 (because we want the frecuency of digits in the position we chose)


    for i in range(1, 10):                      #calculate cumulative count
        count[i] += count[i - 1]

    i = size - 1                                #place the elements in sorted order 
    while i >= 0:
        index = arr[i] // place
        output[count[index % 10] - 1] = arr[i]
        count[index % 10] -= 1
        i -= 1

    for i in range(0, size):                    #gives the array sorted by the place we chose
        arr[i] = output[i]


def radix_sort(arr):
    # Get maximum element
    max_element = np.max(arr)

    # Apply counting sort to sort elements based on place value.
    place = 1
    while max_element // place > 0:
        counting_sort(arr, place)
        place *= 10


In [11]:
def counting_algorithm(arr,place):
    start = time.time()
    counting_sort(arr,place)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

def radix_algorithm(arr):
    start = time.time()
    radix_sort(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [12]:
data = np.random.randint(1,10000,17000)

In [13]:
counting_algorithm(data,1)

The time of execution of above program is : 15.004873275756836 ms for a size of  17000


array([ 420, 7320,  580, ..., 6849, 4359, 4889])

In [14]:
radix_algorithm(data)

The time of execution of above program is : 75.08563995361328 ms for a size of  17000


array([   1,    1,    2, ..., 9996, 9998, 9998])

In [15]:
max=np.max(data)
print(max)
d=np.log10(max)+1
print(d)

9998
4.999913132416571


The order of the radix algorithm is $O(d(n+b))$ where $b=base=10$ and $d=log_{10}(max)+1$. So in this case, $O(f(n))=O(4,99(n+10))$

### Conclusions

- So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!
- Among the sorting algorithms we find linear, loglinear and quadratic order complexities. The difference lies in whether or not there is a comparison between the elements of the array to be sorted and how this comparison is made.